require('dotenv').config();const mongoose=require('mongoose'),bcrypt=require('bcrypt');const User=require('./models/User'),Trainee=require('./models/Trainee'),Provider=require('./models/Provider'),Employer=require('./models/Employer'),Job=require('./models/Job'),FollowUp=require('./models/FollowUp'),Verification=require('./models/Verification'),Course=require('./models/Course'),Enrollment=require('./models/Enrollment'),Assessment=require('./models/Assessment');
(async()=>{await mongoose.connect(process.env.MONGO_URI||'mongodb://127.0.0.1:27017/disha');await Promise.all([User.deleteMany({}),Trainee.deleteMany({}),Provider.deleteMany({}),Employer.deleteMany({}),Job.deleteMany({}),FollowUp.deleteMany({}),Verification.deleteMany({}),Course.deleteMany({}),Enrollment.deleteMany({}),Assessment.deleteMany({})]);
const providers=await Provider.insertMany([{name:'Bihar Skill Development Mission Centre',district:'Patna',contact:'provider@disha.gov.in',courses:['CNC Machining','Data Analytics'],trainees:240,placementRate:64,verified:true},{name:'Udaan Foundation',district:'Gaya',contact:'udaan@disha.gov.in',courses:['Retail & Sales','Power BI'],trainees:180,placementRate:58,verified:true}]);
const employers=await Employer.insertMany([{company:'TechNova Manufacturing',industry:'Manufacturing',district:'Patna',contact:'hr@technova.in',hired:48,verified:true,avgWage:18500},{company:'Retail Connect India',industry:'Retail',district:'Gaya',contact:'hr@retailconnect.in',hired:31,verified:true,avgWage:14200},{company:'DataEdge Services',industry:'IT Services',district:'Bengaluru',contact:'jobs@dataedge.in',hired:22,verified:false,avgWage:26500}]);
const courses=await Course.insertMany([
{code:'GOV-DA-101',title:'Data Analytics',sector:'IT & Data',description:'Learn spreadsheets, SQL, dashboards and data-driven decision making.',skills:['Excel','SQL','Power BI','Python'],duration:'3 Months',mode:'Offline + Digital',eligibility:'12th / Graduate / Diploma',provider:providers[0].name,district:'Patna',seats:48,fee:'Government Sponsored',certification:true,certificateName:'Skill India Certificate',scheme:'Government Skilling Programme',startDate:'2026-09-15'},
{code:'GOV-WEB-102',title:'Web Development',sector:'IT',description:'Build modern websites and web applications using HTML, CSS and JavaScript.',skills:['HTML','CSS','JavaScript','React Basics'],duration:'4 Months',mode:'Hybrid',eligibility:'12th or above',provider:providers[1].name,district:'Gaya',seats:36,fee:'Government Sponsored',certification:true,certificateName:'Skill India Certificate',scheme:'Government Skilling Programme',startDate:'2026-09-20'},
{code:'GOV-CNC-103',title:'CNC Machining',sector:'Manufacturing',description:'Hands-on training for CNC operation, safety and quality practices.',skills:['CNC Operation','Safety','Quality Control'],duration:'6 Months',mode:'Offline',eligibility:'10th / ITI / Diploma',provider:providers[0].name,district:'Patna',seats:22,fee:'Government Sponsored',certification:true,certificateName:'Skill India Certificate',scheme:'Government Skilling Programme',startDate:'2026-09-10'},
{code:'GOV-RET-104',title:'Retail & Sales',sector:'Retail',description:'Customer service, sales, billing and digital retail fundamentals.',skills:['Sales','Customer Service','CRM','Digital Retail'],duration:'3 Months',mode:'Offline + Digital',eligibility:'10th or above',provider:providers[1].name,district:'Gaya',seats:55,fee:'Government Sponsored',certification:true,certificateName:'Skill India Certificate',scheme:'Government Skilling Programme',startDate:'2026-09-18'},
{code:'GOV-SOL-105',title:'Solar PV Technician',sector:'Green Jobs',description:'Installation, maintenance and safety for solar photovoltaic systems.',skills:['Electrical Basics','Solar Installation','Safety'],duration:'4 Months',mode:'Offline',eligibility:'10th / ITI',provider:providers[0].name,district:'Patna',seats:28,fee:'Government Sponsored',certification:true,certificateName:'Skill India Certificate',scheme:'Green Skills Initiative',startDate:'2026-10-01'}
]);
const data=[
 ['TR-8801','Aman Kumar','aman@example.com','CNC Machining','Gaya',providers[1].name,'employed',18500,'TechNova Manufacturing',true,['CNC','Safety'],['Quality Control'],'Male','18-24','Diploma'],
 ['TR-8802','Priya Singh','priya@example.com','Data Analytics','Patna',providers[0].name,'job_search',0,'',false,['Excel','SQL'],['Power BI','Communication'],'Female','18-24','Graduate'],
 ['TR-8803','Ravi Kumar','ravi@example.com','Retail & Sales','East Champaran',providers[1].name,'certified',0,'',false,['Sales','CRM'],['Digital Sales'],'Male','25-34','12th'],
 ['TR-8804','Neha Sharma','neha@example.com','CNC Machining','Patna',providers[0].name,'employed',16200,'TechNova Manufacturing',false,['CNC','Quality'],['Safety'],'Female','18-24','Diploma'],
 ['TR-8805','Sahil Verma','sahil@example.com','Data Analytics','Bhagalpur',providers[0].name,'self_employed',21000,'',false,['Excel','SQL','Power BI'],['Business Finance'],'Male','25-34','Graduate'],
 ['TR-8806','Kiran Devi','kiran@example.com','Retail & Sales','Gaya',providers[1].name,'training',0,'',false,['Customer Service'],['Communication'],'Female','25-34','12th'],
 ['TR-8807','Pooja Kumari','pooja@example.com','Power BI','Patna',providers[0].name,'apprenticeship',12000,'DataEdge Services',false,['Power BI','Excel'],['SQL'],'Female','18-24','Graduate'],
 ['TR-8808','Imran Ali','imran@example.com','Retail & Sales','Muzaffarpur',providers[1].name,'dropped_out',0,'',false,['Sales'],['Digital Skills'],'Male','18-24','10th']
];
const trainees=await Trainee.insertMany(data.map((x,i)=>({traineeId:x[0],name:x[1],email:x[2],course:x[3],district:x[4],provider:x[5],status:x[6],trainingStatus:['training','certified','dropped_out'].includes(x[6])?x[6]:'certified',attendance: i===7?28:78+i*2,assessmentScore:i===7?0:62+i*4,certificateId:(i===0||i===3)?`DISHA-CERT-2026-${x[0]}`:'',wage:x[7],employer:x[8],employerVerified:x[9],verificationStatus:x[9]?'verified':(x[8]?'pending':'not_requested'),skills:x[10],skillGap:x[11],consent:true,consentDate:'2026-04-15',demographics:{gender:x[12],ageGroup:x[13],education:x[14]},retention:{month3:i===0||i===3,month6:i===0,month12:false},selfEmployment:x[6]==='self_employed'?{businessName:'Local Analytics Services',sector:'Services',monthlyIncome:21000}:{},apprenticeship:x[6]==='apprenticeship'?{organization:'DataEdge Services',trade:'Business Intelligence',stipend:12000,startDate:'2026-06-01'}:{},nonPlacementReason:x[6]==='job_search'?'Limited Power BI portfolio':x[6]==='certified'?'Awaiting placement drive':'',attritionReason:x[6]==='dropped_out'?'Relocated and could not continue':'',wageHistory:x[7]?[{amount:x[7],month:'2026-08',source:x[9]?'employer':'self',verified:x[9]}]:[]})));
await Enrollment.create({traineeId:trainees[0].traineeId,courseId:courses[2]._id,courseCode:courses[2].code,courseTitle:courses[2].title,status:'certified',enrolledAt:new Date('2026-02-01'),completedAt:new Date('2026-07-15'),certificateId:trainees[0].certificateId});

const moduleTemplates={
 'Data Analytics':['Level 1 · Spreadsheet Foundations','Level 2 · SQL & Data Querying','Level 3 · Power BI Dashboard Project'],
 'Web Development':['Level 1 · HTML & CSS Foundations','Level 2 · JavaScript & DOM','Level 3 · Responsive Project Exam'],
 'CNC Machining':['Level 1 · Machine & Safety Basics','Level 2 · CNC Operation','Level 3 · Quality Control Practical'],
 'Retail & Sales':['Level 1 · Customer Service','Level 2 · Sales & Billing','Level 3 · Digital Retail Simulation'],
 'Solar PV Technician':['Level 1 · Electrical Safety','Level 2 · Solar Installation','Level 3 · Maintenance Practical'],
 'Power BI':['Level 1 · Data Modelling','Level 2 · DAX & Measures','Level 3 · Interactive Dashboard Project']
};
const courseByTitle=Object.fromEntries(courses.map(c=>[c.title,c]));
const assessmentRows=[];
trainees.forEach((t,idx)=>{const c=courseByTitle[t.course];const mods=moduleTemplates[t.course]||['Level 1 · Foundation','Level 2 · Core Skills','Level 3 · Practical Exam'];let scores=[84,86,88];if(t.traineeId==='TR-8802')scores=[72,64,0];if(t.traineeId==='TR-8803')scores=[83,79,0];if(t.traineeId==='TR-8806')scores=[58,0,0];if(t.traineeId==='TR-8808')scores=[0,0,0];mods.forEach((m,i)=>assessmentRows.push({traineeId:t.traineeId,courseId:c?._id,courseTitle:t.course,moduleKey:`L${i+1}`,level:i+1,moduleName:m,type:i===2?'Final Practical / Project':'Module Assessment',score:scores[i],status:scores[i]===0?'not_started':scores[i]>=80?'passed':'needs_improvement',skillGaps:scores[i]>=80?[]:(i===1?['Advanced practice','Applied problem solving']:['Core concepts']),attempts:scores[i]?1:0,evaluatedBy:scores[i]?providers[idx%2].name:'',evaluatedAt:scores[i]?new Date():undefined}));});
await Assessment.insertMany(assessmentRows);

const pw=await bcrypt.hash('disha123',10);await User.insertMany([{name:'DISHA Super Admin',email:'admin@disha.gov.in',password:pw,role:'admin'},{name:'Udaan Provider',email:'provider@disha.gov.in',password:pw,role:'provider',linkedId:providers[1]._id},{name:'TechNova HR',email:'employer@disha.gov.in',password:pw,role:'employer',linkedId:employers[0]._id},{name:'Aman Kumar',email:'aman@example.com',password:pw,role:'trainee',linkedId:trainees[0]._id}]);
await Job.insertMany([{title:'CNC Operator',company:'TechNova Manufacturing',location:'Patna',skills:['CNC','Safety'],salary:'₹16,000–₹22,000',description:'Operate CNC machines and maintain quality standards.'},{title:'Retail Associate',company:'Retail Connect India',location:'Gaya',skills:['Sales','Customer Service'],salary:'₹12,000–₹18,000',description:'Customer handling and retail operations.'},{title:'Junior Data Analyst',company:'DataEdge Services',location:'Remote / Bengaluru',skills:['Excel','SQL','Power BI'],salary:'₹20,000–₹32,000',description:'Reporting and dashboard analysis.'}]);
await FollowUp.insertMany([{traineeId:'TR-8802',traineeName:'Priya Singh',type:'Employment outcome',stage:'3-month',dueDate:'2026-09-02',owner:'Placement Officer',status:'pending',channel:'phone',notes:'Check job applications and Power BI upskilling.'},{traineeId:'TR-8803',traineeName:'Ravi Kumar',type:'Placement assistance',stage:'Post-certification',dueDate:'2026-09-05',owner:'DISHA Admin',status:'pending',channel:'call',notes:'Recommend suitable retail vacancies.'},{traineeId:'TR-8801',traineeName:'Aman Kumar',type:'Retention check',stage:'6-month',dueDate:'2026-09-10',owner:'Udaan Provider',status:'pending',channel:'phone',notes:'Confirm continued employment and wage progression.'}]);
await Verification.insertMany([{traineeId:'TR-8804',traineeName:'Neha Sharma',employer:'TechNova Manufacturing',employerId:employers[0]._id,claimType:'employment',claimedWage:16200,status:'pending'},{traineeId:'TR-8807',traineeName:'Pooja Kumari',employer:'DataEdge Services',employerId:employers[2]._id,claimType:'apprenticeship',claimedWage:12000,status:'pending'}]);
console.log('Seed complete. Demo password for all accounts: disha123');await mongoose.disconnect();})();
